server:
  port: 9092
spring:
  application:
    name: shiro-rbac-system
  resources:
    static-locations: classpath:/
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .html
    content-type: text/html
    charset: UTF-8
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://pgm-uf62xt6816e2448kho.pg.rds.aliyuncs.com:1921/forecast-test
    username: bitest
    password: WjX5kvucYcr4zDoO
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false # 禁用 OSIV <Spring Boot中默认启用了OSIV(Open Session in View)>
  http:
    encoding:
      charset: utf-8
      enabled: true
